In [2]:
# 조기 종료를 사용한 배치 경사 하강법으로 소프트맥스 회귀를 구현해 보세요 (사이킷런은 사용하지 마세요.)

$$\hat p_k = \sigma(s(\mathbf {x}))_k = {exp(s_k(\mathbf {x}) \over \sum_{j=1}^K exp(s_j(\mathbf {x}))}$$

$$s_k(\mathbf {x}) = (\theta^{(k)})^T \mathbf {x}$$

$$\hat {y} = \underset{k} {argmax} \ \sigma(s(\mathbf {x}))_k = \underset{k} {argmax} \ s_k(\mathbf {x})
= \underset{k} {argmax} \ ((\theta^{(k)})^T \mathbf {x})$$

$$J(\Theta) = - {1 \over m} \sum_{i=1}^m \sum_{k=1}^K y_k^{(i)} log(\hat p_k^{(i)})$$

$$\nabla_{\theta^{(k)}}J(\Theta) = {1 \over m} \sum_{i=1}^m (\hat {p}_k^{(i)} - y_k^{(i)}) \mathbf {x}^{(i)}$$

$$\theta^{(next\;step)} = \theta - \eta \nabla_\theta MSE(\theta)$$

In [102]:
import numpy as np

In [115]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris["data"][:, (2, 3)]
y = iris["target"]

In [116]:
X = np.c_[np.ones([X.shape[0], 1]), X]

In [117]:
print(X)

[[1.  1.4 0.2]
 [1.  1.4 0.2]
 [1.  1.3 0.2]
 [1.  1.5 0.2]
 [1.  1.4 0.2]
 [1.  1.7 0.4]
 [1.  1.4 0.3]
 [1.  1.5 0.2]
 [1.  1.4 0.2]
 [1.  1.5 0.1]
 [1.  1.5 0.2]
 [1.  1.6 0.2]
 [1.  1.4 0.1]
 [1.  1.1 0.1]
 [1.  1.2 0.2]
 [1.  1.5 0.4]
 [1.  1.3 0.4]
 [1.  1.4 0.3]
 [1.  1.7 0.3]
 [1.  1.5 0.3]
 [1.  1.7 0.2]
 [1.  1.5 0.4]
 [1.  1.  0.2]
 [1.  1.7 0.5]
 [1.  1.9 0.2]
 [1.  1.6 0.2]
 [1.  1.6 0.4]
 [1.  1.5 0.2]
 [1.  1.4 0.2]
 [1.  1.6 0.2]
 [1.  1.6 0.2]
 [1.  1.5 0.4]
 [1.  1.5 0.1]
 [1.  1.4 0.2]
 [1.  1.5 0.2]
 [1.  1.2 0.2]
 [1.  1.3 0.2]
 [1.  1.4 0.1]
 [1.  1.3 0.2]
 [1.  1.5 0.2]
 [1.  1.3 0.3]
 [1.  1.3 0.3]
 [1.  1.3 0.2]
 [1.  1.6 0.6]
 [1.  1.9 0.4]
 [1.  1.4 0.3]
 [1.  1.6 0.2]
 [1.  1.4 0.2]
 [1.  1.5 0.2]
 [1.  1.4 0.2]
 [1.  4.7 1.4]
 [1.  4.5 1.5]
 [1.  4.9 1.5]
 [1.  4.  1.3]
 [1.  4.6 1.5]
 [1.  4.5 1.3]
 [1.  4.7 1.6]
 [1.  3.3 1. ]
 [1.  4.6 1.3]
 [1.  3.9 1.4]
 [1.  3.5 1. ]
 [1.  4.2 1.5]
 [1.  4.  1. ]
 [1.  4.7 1.4]
 [1.  3.6 1.3]
 [1.  4.4 1.4]
 [1.  4.5 

In [118]:
np.random.seed(2042)

In [119]:
test_ratio = 0.2
validationn_ratio = 0.2
total_size = len(X)

test_size = int(total_size * test_ratio)
validation_size = int(total_size * validationn_ratio)
train_size = total_size - test_size - validation_size

rnd_indices = np.random.permutation(total_size)

X_train = X[rnd_indices[:train_size]]
y_train = y[rnd_indices[:train_size]]
X_valid = X[rnd_indices[train_size:-test_size]]
y_valid = y[rnd_indices[train_size:-test_size]]
X_test = X[rnd_indices[-test_size:]]
y_test = y[rnd_indices[-test_size:]]

In [120]:
def softmax(logit):
    return np.exp(logit) / np.sum(np.exp(logit), axis=1, keepdims=True)

In [121]:
def one_hot(y):
    y_one_hot = (y == 0)
    for i in range(1, len(np.unique(y))):
        y_one_hot = np.c_[y_one_hot, (y == i)]
    
    return y_one_hot

In [110]:
def softmax_regression(X, y, eta, epsilon, n_epochs):
    Theta = np.random.rand(X.shape[1], len(np.unique(y)))
    
    for epoch in range(n_epochs):
        logit = X.dot(Theta)
        if epoch % 100 == 0:
            loss = -np.mean(np.sum(one_hot(y) * np.log(softmax(logit) + epsilon), axis=1))
            print(epoch, loss)
        Theta = Theta - eta * (1 / X.shape[0]) * X.T.dot(softmax(logit) - one_hot(y))
        
    return Theta

In [111]:
Theta = softmax_regression(X_train, y_train, 0.01, 1e-7, 5001)

0 2.1041298095182546
100 0.9773253549775368
200 0.9244827149782782
300 0.8772659673940222
400 0.835134154553148
500 0.7975963791730117
600 0.7641553224875609
700 0.7343316692051317
800 0.707679967227584
900 0.6837971094678368
1000 0.6623252726598646
1100 0.6429511477455903
1200 0.6254029728082421
1300 0.6094464693370865
1400 0.5948804114237712
1500 0.5815322702225296
1600 0.5692541745220324
1700 0.5579192971369724
1800 0.5474186970886771
1900 0.537658602630962
2000 0.52855809752725
2100 0.5200471638364138
2200 0.5120650330465584
2300 0.5045588000737211
2400 0.497482259219808
2500 0.4907949263916581
2600 0.4844612170284537
2700 0.47844975392307776
2800 0.47273278331190705
2900 0.4672856812168731
3000 0.4620865350818338
3100 0.4571157883076949
3200 0.45235593742176605
3300 0.44779127338056784
3400 0.4434076599606987
3500 0.4391923433913653
3600 0.4351337883693733
3700 0.4312215364102865
3800 0.42744608315937294
3900 0.423798771838657
4000 0.4202717004630981
4100 0.4168576408369544
4200 0

In [112]:
logits = X_valid.dot(Theta)
y_predict = np.argmax(softmax(logits), axis=1)

accuracy_score = np.mean(y_predict == y_valid)
accuracy_score

0.9666666666666667

In [126]:
def softmax_regression(X, y, eta, alpha, epsilon, n_epochs):
    Theta = np.random.rand(X.shape[1], len(np.unique(y)))
    
    for epoch in range(n_epochs):
        logit = X.dot(Theta)
        if epoch % 100 == 0:
            xentropy_loss = -np.mean(np.sum(one_hot(y) * np.log(softmax(logit) + epsilon), axis=1))
            l2_loss = (1/2) * np.sum(np.square(Theta[1:])) 
            loss = xentropy_loss + alpha * l2_loss
            print(epoch, loss)
        Theta = Theta - eta * ((1 / X.shape[0]) * X.T.dot(softmax(logit) - one_hot(y)) + np.r_[np.zeros([1, Theta.shape[1]]), alpha * Theta[1:]])
        
    return Theta

In [127]:
Theta = softmax_regression(X_train, y_train, 0.1, 0.1, 1e-7, 5001)

0 1.1286867269609013
100 0.727001520381528
200 0.6172511945261256
300 0.5722314799724413
400 0.5483493547391751
500 0.5336165724232963
600 0.5236333077278472
700 0.5164448128733705
800 0.5110553848619248
900 0.506901544340828
1000 0.5036368734426767
1100 0.5010341406487107
1200 0.4989366341361362
1300 0.4972320351851622
1400 0.4958374238613538
1500 0.49469016215995615
1600 0.4937420710690712
1700 0.4929555543676384
1800 0.4923009279797319
1900 0.49175452675278375
2000 0.49129733027502115
2100 0.4909139456052336
2200 0.4905918416541769
2300 0.4903207648191134
2400 0.49009228756446294
2500 0.4898994560562627
2600 0.4897365126090409
2700 0.48959867531266066
2800 0.4894819618232197
2900 0.48938304758370466
3000 0.48929915110927685
3100 0.4892279407063359
3200 0.48916745827987496
3300 0.4891160568470703
3400 0.4890723491045481
3500 0.4890351649543214
3600 0.48900351632314565
3700 0.4889765679438932
3800 0.48895361302877094
3900 0.4889340529699576
4000 0.4889173803662827
4100 0.4889031648045

In [128]:
logits = X_valid.dot(Theta)
y_predict = np.argmax(softmax(logits), axis=1)

accuracy_score = np.mean(y_predict == y_valid)
accuracy_score

1.0

In [ ]:
def softmax_regression(X_train, y_train, X_val, y_val, eta, alpha, epsilon, n_epochs):
    Theta = np.random.rand(X_train.shape[1], len(np.unique(y_train)))
    best_loss = np.infty
    
    for epoch in range(n_epochs):
        logit = X_train.dot(Theta)
        Theta = Theta - eta * ((1 / X_train.shape[0]) * X_train.T.dot(softmax(logit) - one_hot(y_train)) + np.r_[np.zeros([1, Theta.shape[1]]), alpha * Theta[1:]])
        
        logit = X_valid.dot(Theta)
        xentropy_loss = -np.mean(np.sum(one_hot(y_val) * np.log(softmax(logit) + epsilon), axis=1))
        l2_loss = (1/2) * np.sum(np.square(Theta[1:])) 
        loss = xentropy_loss + alpha * l2_loss
        
        if epoch % 100 == 0:
            print(epoch, loss)
        if loss < best_loss:
            best_loss = loss
        else:
            print(epoch - 1, best_loss)
            print(epoch, loss, "조기 종료!")
            return Theta
            
    return Theta

In [ ]:
logits = X_valid.dot(Theta)
y_predict = np.argmax(softmax(logits), axis=1)

accuracy_score = np.mean(y_predict == y_valid)
accuracy_score